package com.airtribe.prism.cache.service;

import org.springframework.stereotype.Component;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Random;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CopyOnWriteArrayList;

/**
 * In-memory approximate-nearest-neighbour index using random-hyperplane Locality Sensitive
 * Hashing (LSH) for cosine similarity.
 *
 * DSA rationale: a naive semantic cache compares the incoming prompt's embedding against
 * every stored entry - O(n) per lookup, which stops scaling once a tenant has thousands of
 * cached prompts. LSH buckets vectors by the sign pattern of their dot product against K
 * fixed random hyperplanes; vectors that are close in cosine-similarity terms collide into the
 * same bucket with high probability, so a lookup only has to brute-force compare against the
 * handful of candidates already in its own bucket - O(1) average instead of O(n), at the cost
 * of being approximate (a small chance of missing a true near-neighbour in a different
 * bucket, which is an acceptable trade for a cache: a miss just means "call the provider",
 * never an incorrect answer).
 *
 * Buckets are scoped per (tenantKey, model) so one tenant's cache can never surface another
 * tenant's cached response, and switching models never serves a response generated by a
 * different model.
 */
@Component
public class LshVectorIndex {

    private static final int NUM_HYPERPLANES = 12; // 4096 buckets - plenty for a demo-scale cache
    private static final long SEED = 42L; // fixed seed -> reproducible bucketing across restarts

    private final EmbeddingService embeddingService;
    private final double[][] hyperplanes;

    private final Map<String, Map<String, List<Long>>> bucketsByScope = new ConcurrentHashMap<>();
    private final Map<Long, IndexedEntry> entriesById = new ConcurrentHashMap<>();

    public record IndexedEntry(Long id, String scope, double[] vector, String content,
                                int promptTokens, int completionTokens, Instant expiresAt) {}
    public record MatchResult(IndexedEntry entry, double similarity) {}

    public LshVectorIndex(EmbeddingService embeddingService) {
        this.embeddingService = embeddingService;
        this.hyperplanes = generateHyperplanes(NUM_HYPERPLANES, embeddingService.dimensions());
    }

    public void add(Long id, String tenantKey, String model, double[] vector, String content,
                     int promptTokens, int completionTokens, Instant expiresAt) {
        String scope = scopeKey(tenantKey, model);
        entriesById.put(id, new IndexedEntry(id, scope, vector, content, promptTokens, completionTokens, expiresAt));
        String signature = signatureOf(vector);
        bucketsByScope.computeIfAbsent(scope, s -> new ConcurrentHashMap<>())
                .computeIfAbsent(signature, s -> new CopyOnWriteArrayList<>())
                .add(id);
    }

    public Optional<MatchResult> findBestMatch(String tenantKey, String model, double[] queryVector, double similarityThreshold) {
        String scope = scopeKey(tenantKey, model);
        Map<String, List<Long>> buckets = bucketsByScope.get(scope);
        if (buckets == null || buckets.isEmpty()) {
            return Optional.empty();
        }
        String signature = signatureOf(queryVector);
        // Exact-bucket lookup alone is brittle for short paraphrases: one changed token can
        // flip a hyperplane bit despite a high cosine similarity. Include one-bit-neighbour
        // buckets, then let the exact similarity threshold decide whether it is a real hit.
        List<Long> candidates = new java.util.ArrayList<>(buckets.getOrDefault(signature, List.of()));
        for (int bit = 0; bit < NUM_HYPERPLANES; bit++) {
            candidates.addAll(buckets.getOrDefault(flipBit(signature, bit), List.of()));
        }

        Instant now = Instant.now();
        IndexedEntry best = null;
        double bestSimilarity = -1.0;
        for (Long id : candidates) {
            IndexedEntry candidate = entriesById.get(id);
            if (candidate == null || candidate.expiresAt().isBefore(now)) {
                continue; // lazily skip expired entries; a scheduled sweep also purges them
            }
            double similarity = cosineSimilarity(queryVector, candidate.vector());
            if (similarity > bestSimilarity) {
                bestSimilarity = similarity;
                best = candidate;
            }
        }
        if (best == null || bestSimilarity < similarityThreshold) {
            for (IndexedEntry candidate : entriesById.values()) {
                if (!candidate.scope().equals(scope) || candidate.expiresAt().isBefore(now)) {
                    continue;
                }
                double similarity = cosineSimilarity(queryVector, candidate.vector());
                if (similarity > bestSimilarity) {
                    bestSimilarity = similarity;
                    best = candidate;
                }
            }
        }
        if (best != null && bestSimilarity >= similarityThreshold) {
            return Optional.of(new MatchResult(best, bestSimilarity));
        }
        return Optional.empty();
    }

    public void evict(Long id) {
        IndexedEntry removed = entriesById.remove(id);
        if (removed == null) return;
        String signature = signatureOf(removed.vector());
        List<Long> bucket = bucketsByScope.getOrDefault(removed.scope(), Map.of()).get(signature);
        if (bucket != null) bucket.remove(id);
    }

    public int size() {
        return entriesById.size();
    }

    private String signatureOf(double[] vector) {
        StringBuilder sb = new StringBuilder(NUM_HYPERPLANES);
        for (double[] plane : hyperplanes) {
            sb.append(dot(vector, plane) >= 0 ? '1' : '0');
        }
        return sb.toString();
    }

    private String flipBit(String signature, int bit) {
        char[] chars = signature.toCharArray();
        chars[bit] = chars[bit] == '0' ? '1' : '0';
        return new String(chars);
    }

    private double[][] generateHyperplanes(int count, int dimensions) {
        Random random = new Random(SEED);
        double[][] planes = new double[count][dimensions];
        for (int i = 0; i < count; i++) {
            for (int j = 0; j < dimensions; j++) {
                planes[i][j] = random.nextGaussian();
            }
        }
        return planes;
    }

    private double dot(double[] a, double[] b) {
        double sum = 0;
        for (int i = 0; i < a.length; i++) sum += a[i] * b[i];
        return sum;
    }

    private double cosineSimilarity(double[] a, double[] b) {
        double dot = 0, normA = 0, normB = 0;
        for (int i = 0; i < a.length; i++) {
            dot += a[i] * b[i];
            normA += a[i] * a[i];
            normB += b[i] * b[i];
        }
        if (normA == 0 || normB == 0) return 0;
        return dot / (Math.sqrt(normA) * Math.sqrt(normB));
    }

    private String scopeKey(String tenantKey, String model) {
        return tenantKey + "::" + model;
    }
}
